app:
    resource: '@AppBundle/Controller/'
    type: annotation

domains:
    type:     rest
    resource: AppBundle\Controller\DomainController

# mailers:
#     type:     rest
#     resource: AppBundle\Controller\MailerController
